<?php

namespace ContainerXct5Ybz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PaymentController' shared autowired service.
     *
     * @return \App\Controller\PaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PaymentController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PriceCalculatorService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PaymentService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/PaymentProcessorFactory.php';

        $a = new \App\Service\PriceCalculatorService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\TaxRepository'] ?? $container->load('getTaxRepositoryService')), ($container->privates['App\\Repository\\CouponRepository'] ?? $container->load('getCouponRepositoryService')));

        $container->services['App\\Controller\\PaymentController'] = $instance = new \App\Controller\PaymentController(($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)), $a, new \App\Service\PaymentService(new \App\Service\Payment\PaymentProcessorFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Service\\Payment\\PaypalPaymentAdapter'] ?? $container->load('getPaypalPaymentAdapterService'));
            yield 1 => ($container->privates['App\\Service\\Payment\\StripePaymentAdapter'] ?? $container->load('getStripePaymentAdapterService'));
        }, 2)), $a));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'serializer' => '?',
            'twig' => '?',
        ]))->withContext('App\\Controller\\PaymentController', $container));

        return $instance;
    }
}
