<?php

namespace ContainerXct5Ybz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidTaxNumberValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\ValidTaxNumberValidator' shared autowired service.
     *
     * @return \App\Validator\ValidTaxNumberValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ValidTaxNumberValidator.php';

        return $container->privates['App\\Validator\\ValidTaxNumberValidator'] = new \App\Validator\ValidTaxNumberValidator(($container->privates['App\\Repository\\TaxRepository'] ?? $container->load('getTaxRepositoryService')));
    }
}
