<?php

namespace ContainerZAx4sQ0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripePaymentAdapterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Payment\StripePaymentAdapter' shared autowired service.
     *
     * @return \App\Service\Payment\StripePaymentAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/PaymentProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/StripePaymentAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/systemeio/test-for-candidates/src/PaymentProcessor/StripePaymentProcessor.php';

        return $container->privates['App\\Service\\Payment\\StripePaymentAdapter'] = new \App\Service\Payment\StripePaymentAdapter(new \Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor());
    }
}
