<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfJlY9b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfJlY9b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRfJlY9b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRfJlY9b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRfJlY9b\App_KernelDevDebugContainer([
    'container.build_hash' => 'RfJlY9b',
    'container.build_id' => '76cbf325',
    'container.build_time' => 1769019860,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfJlY9b');
