<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'calculate_price' => [[], ['_controller' => 'App\\Controller\\PaymentController::calculatePrice'], [], [['text', '/calculate-price']], [], [], []],
    'purchase' => [[], ['_controller' => 'App\\Controller\\PaymentController::purchase'], [], [['text', '/purchase']], [], [], []],
    'App\Controller\PaymentController::calculatePrice' => [[], ['_controller' => 'App\\Controller\\PaymentController::calculatePrice'], [], [['text', '/calculate-price']], [], [], []],
    'App\Controller\PaymentController::purchase' => [[], ['_controller' => 'App\\Controller\\PaymentController::purchase'], [], [['text', '/purchase']], [], [], []],
];
